export const CLIENT_INDUSTRY_OPTIONS = [
  "SaaS",
  "E-commerce",
  "Healthcare",
  "Finance",
  "Education",
  "Real Estate",
  "Hospitality",
  "Restaurant",
  "Bar & Nightlife",
  "Retail",
  "Travel & Tourism",
  "Fitness & Wellness",
  "Beauty & Salon",
  "Automotive",
  "Events & Entertainment",
  "Non-Profit",
  "Other",
];
