import React from "react";
import { getPlatformMeta, getStatusMeta, formatDateDisplay, getWeekDay } from "./constants";

const STATUS_PRINT_COLORS = { pending: "#b45309", scheduled: "#1d4ed8", posted: "#15803d" };

const DEFAULT_VISIBLE_COLUMNS = {
  date: true,
  day: true,
  client: false,
  holiday: false,
  postTitle: true,
  content: false, // Suggestions / Notes hidden by default for client presentation
  caption: true,
  hashtags: true,
  platforms: true,
  creatives: false, // Image links hidden by default for client presentation
  status: true,
};

export default function ContentCalendarPrintView({
  entries = [],
  title = "Content Calendar",
  subtitle = "",
  visibleColumns = DEFAULT_VISIBLE_COLUMNS,
  brandColor = "#4f46e5",
  clientLogo = null,
  agencyName = "Social Buzz Media",
  compactness = "standard", // "compact" | "standard" | "relaxed"
}) {
  const generatedOn = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const paddingY = compactness === "compact" ? "6px" : compactness === "relaxed" ? "12px" : "8px";
  const paddingX = compactness === "compact" ? "8px" : compactness === "relaxed" ? "14px" : "10px";
  const bodyFontSize = compactness === "compact" ? "11px" : compactness === "relaxed" ? "13px" : "12px";

  const th = {
    padding: `${paddingY} ${paddingX}`,
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontWeight: "700",
    color: "#374151",
    background: "#f8fafc",
    border: "1px solid #cbd5e1",
    textAlign: "left",
    whiteSpace: "nowrap",
  };

  const td = {
    padding: `${paddingY} ${paddingX}`,
    fontSize: bodyFontSize,
    color: "#1f2937",
    border: "1px solid #e2e8f0",
    verticalAlign: "top",
    maxWidth: "280px",
    wordBreak: "break-word",
    lineHeight: "1.45",
  };

  return (
    <div
      style={{
        width: "fit-content",
        minWidth: "800px",
        background: "#ffffff",
        padding: "32px",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      }}
    >
      {/* Header Banner */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "20px", borderBottom: `2px solid ${brandColor}`, paddingBottom: "14px" }}>
        <div>
          <h1 style={{ fontSize: "22px", fontWeight: 800, color: "#0f172a", margin: 0, letterSpacing: "-0.02em" }}>
            {title}
          </h1>
          {subtitle ? (
            <p style={{ fontSize: "13px", color: "#475569", margin: "4px 0 0", fontWeight: 500 }}>{subtitle}</p>
          ) : (
            <p style={{ fontSize: "11px", color: "#64748b", margin: "4px 0 0" }}>
              Generated by {agencyName} · {entries.length} Scheduled Items
            </p>
          )}
        </div>
        <div style={{ textAlign: "right" }}>
          {clientLogo && (
            <img
              src={clientLogo}
              alt="Client Logo"
              style={{ maxHeight: "36px", maxWidth: "120px", objectFit: "contain", marginBottom: "4px" }}
            />
          )}
          <p style={{ fontSize: "11px", color: "#64748b", margin: 0 }}>Date: {generatedOn}</p>
        </div>
      </div>

      {/* Main Table */}
      <table style={{ borderCollapse: "collapse", width: "100%", background: "#ffffff" }}>
        <thead>
          <tr>
            {visibleColumns.date && <th style={th}>Date</th>}
            {visibleColumns.day && <th style={th}>Day</th>}
            {visibleColumns.client && <th style={th}>Client</th>}
            {visibleColumns.holiday && <th style={th}>Occasion</th>}
            {visibleColumns.postTitle && <th style={th}>Post Title / Topic</th>}
            {visibleColumns.content && <th style={th}>Suggestions / Ideas</th>}
            {visibleColumns.caption && <th style={th}>Caption / Copy</th>}
            {visibleColumns.hashtags && <th style={th}>Hashtags</th>}
            {visibleColumns.platforms && <th style={th}>Platforms</th>}
            {visibleColumns.creatives && <th style={th}>Creatives / Links</th>}
            {visibleColumns.status && <th style={th}>Status</th>}
          </tr>
        </thead>
        <tbody>
          {entries.map((entry, idx) => {
            const isEven = idx % 2 === 0;
            const rowBg = isEven ? "#ffffff" : "#fcfcfd";

            return (
              <tr key={entry.id || idx} style={{ background: rowBg }}>
                {visibleColumns.date && (
                  <td style={{ ...td, whiteSpace: "nowrap", fontWeight: 600 }}>
                    {formatDateDisplay(entry.date)}
                  </td>
                )}
                {visibleColumns.day && (
                  <td style={{ ...td, whiteSpace: "nowrap", color: "#64748b" }}>
                    {getWeekDay(entry.date)}
                  </td>
                )}
                {visibleColumns.client && (
                  <td style={{ ...td, whiteSpace: "nowrap", fontWeight: 600 }}>
                    {entry.clientName || "—"}
                  </td>
                )}
                {visibleColumns.holiday && (
                  <td style={{ ...td, color: "#9333ea", fontWeight: 500 }}>
                    {entry.holiday || "—"}
                  </td>
                )}
                {visibleColumns.postTitle && (
                  <td style={{ ...td, fontWeight: 600, color: "#0f172a" }}>
                    {entry.postTitle || "—"}
                  </td>
                )}
                {visibleColumns.content && (
                  <td style={{ ...td, color: "#475569", fontStyle: "italic" }}>
                    {entry.content || "—"}
                  </td>
                )}
                {visibleColumns.caption && (
                  <td style={{ ...td, whiteSpace: "pre-wrap" }}>
                    {entry.caption || "—"}
                  </td>
                )}
                {visibleColumns.hashtags && (
                  <td style={{ ...td, color: "#2563eb", fontSize: "11px" }}>
                    {entry.hashtags || "—"}
                  </td>
                )}
                {visibleColumns.platforms && (
                  <td style={{ ...td, whiteSpace: "nowrap" }}>
                    {entry.platforms && entry.platforms.length > 0
                      ? entry.platforms.map((p) => getPlatformMeta(p).label).join(", ")
                      : "—"}
                  </td>
                )}
                {visibleColumns.creatives && (
                  <td style={{ ...td, fontSize: "11px" }}>
                    {entry.creatives && entry.creatives.length > 0
                      ? entry.creatives.map((c, i) => (
                          <div key={c.fileId || `print-c-${entry.id || idx}-${i}`} style={{ marginBottom: "2px" }}>
                            {c.webViewLink || c.driveLink ? (
                              <a
                                href={c.webViewLink || c.driveLink}
                                target="_blank"
                                rel="noreferrer"
                                style={{ color: brandColor, textDecoration: "underline" }}
                              >
                                {c.isPinterest ? "Pinterest Pin" : c.fileName || "View Link"}
                              </a>
                            ) : (
                              c.fileName
                            )}
                          </div>
                        ))
                      : "—"}
                  </td>
                )}
                {visibleColumns.status && (
                  <td
                    style={{
                      ...td,
                      whiteSpace: "nowrap",
                      fontWeight: 700,
                      color: STATUS_PRINT_COLORS[entry.status] || "#b45309",
                    }}
                  >
                    {getStatusMeta(entry.status).label}
                  </td>
                )}
              </tr>
            );
          })}
        </tbody>
      </table>

      {/* Footer */}
      <div style={{ marginTop: "20px", display: "flex", justifyContent: "space-between", fontSize: "10px", color: "#94a3b8" }}>
        <span>{agencyName} · Content Management System</span>
        <span>Confidential & Prepared for Client Review</span>
      </div>
    </div>
  );
}
